

sudo: false
language: node_js
node_js:
  - "node"


install:
  - npm ci

env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - script: COVERALLS_FLAG_NAME=test make test-coveralls

notifications:
  webhooks: https://coveralls.io/webhook

